---
name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [centos7, debian10, ubuntu1804, ubuntu2004]
        pg: [pg11, pg12]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install shunit2
        run: sudo apt-get install -y shunit2
      - name: Build walkthroughs
        run: |
          cd linux
          ./autogenerate.sh
      - name: Build docker image
        if: contains(matrix.pg, 'pg12') || (!contains(matrix.os, 'ubuntu2004') && contains(matrix.pg, 'pg11'))
        run: |
          cd linux/test
          PGVER=$PGVER ./docker-build.sh $ENV
          ./test_services.sh
        env:
          ENV: ${{ matrix.os }}
          PGVER: ${{ matrix.pg }}
